"""SQLite-backed room content catalog.

This database is separate from save_data.db because room templates are
reference content, not mutable player progress.
"""

import os
import sqlite3


_DB_PATH = os.path.join(os.path.dirname(__file__), "room_content.db")

BASE_ROOM_TEMPLATE_TABLE = "base_room_templates"
DUNGEON_ROOM_TEMPLATE_TABLES = {
    "mud_caverns": "mud_caverns_room_templates",
    "frozen_depths": "frozen_depths_room_templates",
    "sunken_ruins": "sunken_ruins_room_templates",
}

ROOM_TEMPLATE_COLUMNS = (
    "room_id",
    "display_name",
    "objective_kind",
    "combat_pressure",
    "decision_complexity",
    "topology_role",
    "min_depth",
    "max_depth",
    "branch_preference",
    "generation_weight",
    "enabled",
    "implementation_status",
    "objective_variant",
    "path_stage_min",
    "path_stage_max",
    "terminal_preference",
    "repeat_cooldown",
    "reward_affinity",
    "objective_rule",
    "objective_duration_ms",
    "enemy_minimum_bonus",
    "enemy_scale_factor",
    "guaranteed_chest",
    "chest_spawn_chance",
    "terrain_patch_count_range",
    "terrain_patch_size_range",
    "clear_center",
    "terminal_chest_lock",
    "objective_entity_count",
    "scripted_wave_sizes",
    "holdout_zone_radius",
    "holdout_zone_min_radius",
    "holdout_zone_shrink_ms",
    "holdout_zone_migrate_ms",
    "holdout_zone_migration_offsets",
    "holdout_relief_count",
    "holdout_relief_delay_ms",
    "holdout_stabilizer_migration_delay_ms",
    "ritual_role_script",
    "ritual_reinforcement_count",
    "ritual_link_mode",
    "ritual_payoff_kind",
    "ritual_payoff_label",
    "ritual_wrong_strike_spawn_count",
    "objective_label",
    "objective_layout_offsets",
    "objective_spawn_offset",
    "objective_patrol_offset",
    "objective_patrol_shape",
    "objective_radius",
    "objective_trigger_padding",
    "objective_max_hp",
    "objective_move_speed",
    "objective_guide_radius",
    "objective_exit_radius",
    "objective_damage_cooldown_ms",
    "puzzle_reinforcement_count",
    "puzzle_stall_duration_ms",
    "puzzle_stabilizer_count",
    "puzzle_stabilizer_hp",
    "puzzle_camp_pulse_damage",
    "puzzle_camp_pulse_interval_ms",
    "puzzle_camp_pulse_grace_ms",
    "puzzle_camp_pulse_radius",
    "trap_intensity_scale",
    "trap_speed_scale",
    "trap_challenge_reward_kind",
    "notes",
)


def _plan_shape(
    *,
    objective_rule="immediate",
    objective_duration_ms=None,
    enemy_minimum_bonus=0,
    enemy_scale_factor=1.0,
    guaranteed_chest=False,
    chest_spawn_chance=None,
    terrain_patch_count_range="",
    terrain_patch_size_range="",
    clear_center=False,
    terminal_chest_lock=False,
    objective_entity_count=0,
    scripted_wave_sizes="",
    holdout_zone_radius=0,
    holdout_zone_min_radius=0,
    holdout_zone_shrink_ms=0,
    holdout_zone_migrate_ms=0,
    holdout_zone_migration_offsets="",
    holdout_relief_count=0,
    holdout_relief_delay_ms=0,
    holdout_stabilizer_migration_delay_ms=0,
    ritual_role_script="",
    ritual_reinforcement_count=0,
    ritual_link_mode="",
    ritual_payoff_kind="",
    ritual_payoff_label="",
    ritual_wrong_strike_spawn_count=0,
    objective_label="",
    objective_layout_offsets="",
    objective_spawn_offset="",
    objective_patrol_offset="",
    objective_patrol_shape="line",
    objective_radius=0,
    objective_trigger_padding=0,
    objective_max_hp=0,
    objective_move_speed=0.0,
    objective_guide_radius=0,
    objective_exit_radius=0,
    objective_damage_cooldown_ms=0,
    puzzle_reinforcement_count=0,
    puzzle_stall_duration_ms=0,
    puzzle_stabilizer_count=0,
    puzzle_stabilizer_hp=0,
    puzzle_camp_pulse_damage=0,
    puzzle_camp_pulse_interval_ms=0,
    puzzle_camp_pulse_grace_ms=0,
    puzzle_camp_pulse_radius=0,
    trap_intensity_scale=1.0,
    trap_speed_scale=1.0,
    trap_challenge_reward_kind="chest_upgrade",
):
    return {
        "objective_rule": objective_rule,
        "objective_duration_ms": objective_duration_ms,
        "enemy_minimum_bonus": enemy_minimum_bonus,
        "enemy_scale_factor": enemy_scale_factor,
        "guaranteed_chest": int(bool(guaranteed_chest)),
        "chest_spawn_chance": chest_spawn_chance,
        "terrain_patch_count_range": terrain_patch_count_range,
        "terrain_patch_size_range": terrain_patch_size_range,
        "clear_center": int(bool(clear_center)),
        "terminal_chest_lock": int(bool(terminal_chest_lock)),
        "objective_entity_count": objective_entity_count,
        "scripted_wave_sizes": scripted_wave_sizes,
        "holdout_zone_radius": holdout_zone_radius,
        "holdout_zone_min_radius": holdout_zone_min_radius,
        "holdout_zone_shrink_ms": holdout_zone_shrink_ms,
        "holdout_zone_migrate_ms": holdout_zone_migrate_ms,
        "holdout_zone_migration_offsets": holdout_zone_migration_offsets,
        "holdout_relief_count": holdout_relief_count,
        "holdout_relief_delay_ms": holdout_relief_delay_ms,
        "holdout_stabilizer_migration_delay_ms": holdout_stabilizer_migration_delay_ms,
        "ritual_role_script": ritual_role_script,
        "ritual_reinforcement_count": ritual_reinforcement_count,
        "ritual_link_mode": ritual_link_mode,
        "ritual_payoff_kind": ritual_payoff_kind,
        "ritual_payoff_label": ritual_payoff_label,
        "ritual_wrong_strike_spawn_count": ritual_wrong_strike_spawn_count,
        "objective_label": objective_label,
        "objective_layout_offsets": objective_layout_offsets,
        "objective_spawn_offset": objective_spawn_offset,
        "objective_patrol_offset": objective_patrol_offset,
        "objective_patrol_shape": objective_patrol_shape,
        "objective_radius": objective_radius,
        "objective_trigger_padding": objective_trigger_padding,
        "objective_max_hp": objective_max_hp,
        "objective_move_speed": objective_move_speed,
        "objective_guide_radius": objective_guide_radius,
        "objective_exit_radius": objective_exit_radius,
        "objective_damage_cooldown_ms": objective_damage_cooldown_ms,
        "puzzle_reinforcement_count": puzzle_reinforcement_count,
        "puzzle_stall_duration_ms": puzzle_stall_duration_ms,
        "puzzle_stabilizer_count": puzzle_stabilizer_count,
        "puzzle_stabilizer_hp": puzzle_stabilizer_hp,
        "puzzle_camp_pulse_damage": puzzle_camp_pulse_damage,
        "puzzle_camp_pulse_interval_ms": puzzle_camp_pulse_interval_ms,
        "puzzle_camp_pulse_grace_ms": puzzle_camp_pulse_grace_ms,
        "puzzle_camp_pulse_radius": puzzle_camp_pulse_radius,
        "trap_intensity_scale": trap_intensity_scale,
        "trap_speed_scale": trap_speed_scale,
        "trap_challenge_reward_kind": trap_challenge_reward_kind,
    }

BASE_ROOM_TEMPLATES = (
    {
        "room_id": "standard_combat",
        "display_name": "Standard Combat",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "low",
        "topology_role": "opener",
        "min_depth": 0,
        "max_depth": 1,
        "branch_preference": "either",
        "generation_weight": 10,
        "enabled": 1,
        "implementation_status": "implemented",
        "objective_variant": "",
        "path_stage_min": 0,
        "path_stage_max": 1,
        "terminal_preference": "avoid",
        "repeat_cooldown": 0,
        "reward_affinity": "any",
        **_plan_shape(),
        "notes": "Baseline kill-all room used to establish pacing and difficulty.",
    },
    {
        "room_id": "escort_protection",
        "display_name": "Escort And Protection",
        "objective_kind": "escort",
        "combat_pressure": "high",
        "decision_complexity": "high",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "main_path",
        "generation_weight": 3,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 1,
        "reward_affinity": "finale",
        **_plan_shape(
            objective_rule="escort_to_exit",
            enemy_minimum_bonus=1,
            enemy_scale_factor=1.25,
            terrain_patch_count_range="1,3",
            terrain_patch_size_range="2,3",
            clear_center=True,
            terminal_chest_lock=True,
            objective_label="Escort",
            objective_spawn_offset="-6,0",
            objective_max_hp=26,
            objective_move_speed=1.2,
            objective_guide_radius=92,
            objective_exit_radius=24,
            objective_damage_cooldown_ms=500,
        ),
        "notes": "Protect a fragile survivor as they advance toward the exit under enemy pressure.",
    },
    {
        "room_id": "escort_bomb_carrier",
        "display_name": "Escort Bomb Carrier",
        "objective_kind": "escort_variant",
        "combat_pressure": "high",
        "decision_complexity": "high",
        "topology_role": "mid_run",
        "min_depth": 3,
        "max_depth": None,
        "branch_preference": "main_path",
        "generation_weight": 2,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 3,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 1,
        "reward_affinity": "finale",
        **_plan_shape(
            objective_rule="escort_bomb_to_exit",
            enemy_minimum_bonus=1,
            enemy_scale_factor=1.0,
            terrain_patch_count_range="1,3",
            terrain_patch_size_range="2,3",
            clear_center=True,
            terminal_chest_lock=True,
            objective_label="Carrier",
            objective_spawn_offset="-6,0",
            objective_max_hp=30,
            objective_move_speed=1.0,
            objective_guide_radius=92,
            objective_exit_radius=24,
            objective_damage_cooldown_ms=500,
        ),
        "notes": "Guide a volatile carrier who only advances once the path is fully cleared.",
    },
    {
        "room_id": "puzzle_gated_doors",
        "display_name": "Puzzle-Gated Doors",
        "objective_kind": "puzzle",
        "combat_pressure": "mid",
        "decision_complexity": "high",
        "topology_role": "wildcard",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 3,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "ordered_plates",
        "path_stage_min": 1,
        "path_stage_max": 3,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="charge_plates",
            terrain_patch_count_range="2,4",
            terrain_patch_size_range="2,3",
            clear_center=True,
            terminal_chest_lock=True,
            objective_entity_count=3,
            objective_label="Seal",
            objective_layout_offsets="-5,-3;5,-3;0,4",
            objective_trigger_padding=10,
            puzzle_reinforcement_count=1,
            puzzle_stall_duration_ms=2500,
        ),
        "notes": "Exit stays locked until the player charges visible seal plates while under combat pressure.",
    },
    {
        "room_id": "survival_holdout",
        "display_name": "Survival Holdout",
        "objective_kind": "survival",
        "combat_pressure": "high",
        "decision_complexity": "low",
        "topology_role": "finale",
        "min_depth": 4,
        "max_depth": None,
        "branch_preference": "main_path",
        "generation_weight": 4,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 4,
        "path_stage_max": 4,
        "terminal_preference": "prefer",
        "repeat_cooldown": 2,
        "reward_affinity": "finale",
        **_plan_shape(
            objective_rule="holdout_timer",
            objective_duration_ms=9000,
            enemy_minimum_bonus=1,
            enemy_scale_factor=1.5,
            terrain_patch_count_range="2,4",
            terrain_patch_size_range="2,3",
            clear_center=True,
            terminal_chest_lock=True,
            scripted_wave_sizes="1,2,3",
            holdout_zone_radius=96,
            holdout_zone_min_radius=56,
            holdout_zone_shrink_ms=7500,
            holdout_zone_migrate_ms=4500,
            holdout_zone_migration_offsets="-5,-3;5,3",
            holdout_relief_count=1,
            holdout_relief_delay_ms=1500,
            holdout_stabilizer_migration_delay_ms=4500,
        ),
        "notes": "Survive until a timer expires while the holdout circle shrinks and migrates between anchors; optional stabilizers delay reinforcements and anchor the current circle for an extra window.",
    },
    {
        "room_id": "ritual_disruption",
        "display_name": "Ritual Disruption",
        "objective_kind": "ritual",
        "combat_pressure": "mid_high",
        "decision_complexity": "high",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 3,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "altar_anchor",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="destroy_altars",
            enemy_minimum_bonus=1,
            enemy_scale_factor=1.25,
            terrain_patch_count_range="2,5",
            terrain_patch_size_range="2,4",
            clear_center=True,
            terminal_chest_lock=True,
            objective_entity_count=3,
            ritual_role_script="summon,pulse,ward",
            ritual_reinforcement_count=2,
            ritual_link_mode="ward_shields_others",
            ritual_payoff_kind="reveal_reliquary",
            ritual_payoff_label="Reliquary",
        ),
        "notes": "Destroy enemy altars, with each destroyed altar enraging the survivors.",
    },
    {
        "room_id": "resource_race",
        "display_name": "Resource Race",
        "objective_kind": "race",
        "combat_pressure": "mid_high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 3,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "relic_cache",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="claim_relic_before_lockdown",
            objective_duration_ms=7000,
            enemy_minimum_bonus=1,
            enemy_scale_factor=1.25,
            guaranteed_chest=True,
            chest_spawn_chance=1.0,
            terrain_patch_count_range="2,4",
            terrain_patch_size_range="2,4",
            clear_center=True,
            scripted_wave_sizes="1,2",
        ),
        "notes": "Secure the contested relic before raiders lock it down as claimant pressure escalates.",
    },
    {
        "room_id": "trap_gauntlet",
        "display_name": "Trap Gauntlet",
        "objective_kind": "traversal",
        "combat_pressure": "low",
        "decision_complexity": "low",
        "topology_role": "branch",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "branch",
        "generation_weight": 2,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "crusher_corridors",
        "path_stage_min": 0,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 1,
        "reward_affinity": "branch",
        **_plan_shape(
            objective_rule="immediate",
            enemy_scale_factor=0.0,
            guaranteed_chest=True,
            chest_spawn_chance=1.0,
            terrain_patch_count_range="6,9",
            terrain_patch_size_range="3,6",
            clear_center=True,
            objective_entity_count=3,
            objective_label="Lane Switch",
            objective_trigger_padding=18,
        ),
        "notes": "Switchable sweeper lanes create a traversal puzzle before the player reaches the reward chest.",
    },
    {
        "room_id": "stealth_passage",
        "display_name": "Stealth Passage",
        "objective_kind": "stealth",
        "combat_pressure": "low",
        "decision_complexity": "high",
        "topology_role": "wildcard",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 1,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 0,
        "path_stage_max": 2,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "branch",
        **_plan_shape(
            objective_rule="avoid_alarm_zones",
            objective_duration_ms=2200,
            enemy_scale_factor=0.0,
            terrain_patch_count_range="1,3",
            terrain_patch_size_range="2,3",
            clear_center=True,
            objective_entity_count=3,
            objective_label="Alarm",
            objective_layout_offsets="-4,-2;4,-2;0,4",
            objective_patrol_offset="0,2",
            objective_patrol_shape="rect",
            objective_radius=34,
        ),
        "notes": "Slip through visible alarm wards before the search phase escalates into a lockdown fight.",
    },
    {
        "room_id": "timed_extraction",
        "display_name": "Timed Extraction",
        "objective_kind": "timed_extraction",
        "combat_pressure": "mid",
        "decision_complexity": "mid_high",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 3,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "relic_cache",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="loot_then_timer",
            objective_duration_ms=8000,
            enemy_minimum_bonus=1,
            enemy_scale_factor=1.0,
            guaranteed_chest=True,
            chest_spawn_chance=1.0,
            terrain_patch_count_range="3,5",
            terrain_patch_size_range="2,4",
            clear_center=True,
            scripted_wave_sizes="1,2",
        ),
        "notes": "Grab a valuable objective and escape before pursuit waves close the route behind you.",
    },
    {
        "room_id": "rune_altar_chamber",
        "display_name": "Rune Altar Chamber",
        "objective_kind": "boon",
        "combat_pressure": "low",
        "decision_complexity": "high",
        "topology_role": "branch",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "branch",
        "generation_weight": 2,
        "enabled": 1,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 0,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 99,
        "reward_affinity": "branch",
        **_plan_shape(
            objective_rule="rune_altar",
            enemy_scale_factor=0.0,
            terrain_patch_count_range="1,2",
            terrain_patch_size_range="2,3",
            clear_center=True,
            objective_entity_count=1,
            objective_label="Rune Altar",
        ),
        "notes": "A chamber housing a rune altar that offers three rune choices, one per slot category.",
    },
    # ── Biome-room expansion: Earth (Mud Caverns) ─────────────────────
    # These rooms reuse standard combat pacing but swap the biome's default
    # terrain patches for hazard tiles handled by ``terrain_effects.py``.
    {
        "room_id": "earth_stalagmite_field",
        "display_name": "Stalagmite Field",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            terrain_patch_count_range="3,5",
            terrain_patch_size_range="2,3",
        ),
        "notes": "Combat room studded with spike patches that tick damage on contact.",
    },
    {
        "room_id": "earth_quicksand_trap",
        "display_name": "Quicksand Trap",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            terrain_patch_count_range="2,4",
            terrain_patch_size_range="2,3",
            objective_label="Quicksand Trap",
        ),
        "notes": "Combat room where quicksand patches drown the player after a few seconds.",
    },
    {
        "room_id": "earth_crystal_vein",
        "display_name": "Crystal Vein",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "branch",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "any",
        "repeat_cooldown": 1,
        "reward_affinity": "branch",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Combat room with destructible crystals that grant short-lived buffs.",
    },
    {
        "room_id": "earth_tremor_chamber",
        "display_name": "Tremor Chamber",
        "objective_kind": "combat",
        "combat_pressure": "mid_high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
            terrain_patch_count_range="3,4",
            terrain_patch_size_range="2,2",
        ),
        "notes": "Periodic tremors stun anyone not standing on hearth tiles.",
    },
    {
        "room_id": "earth_mushroom_grove",
        "display_name": "Mushroom Grove",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Spore mushrooms periodically poison anyone in their pulse ring; destroy them to silence them.",
    },
    {
        "room_id": "earth_cave_in",
        "display_name": "Cave-In",
        "objective_kind": "combat",
        "combat_pressure": "mid_high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Telegraphed tile collapses turn the floor into lethal pits over time.",
    },
    {
        "room_id": "earth_mining_carts",
        "display_name": "Mining Carts",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Auto-rolling carts trundle along rails; cross between cycles or get knocked aside.",
    },
    {
        "room_id": "earth_burrower_den",
        "display_name": "Burrower Den",
        "objective_kind": "combat",
        "combat_pressure": "mid_high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Telegraphed burrows spit fresh enemies into the room every few seconds.",
    },
    {
        "room_id": "earth_echo_cavern",
        "display_name": "Echo Cavern",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "high",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "branch",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Vision narrows to a tight circle; enemies prowl the darkness.",
    },
    {
        "room_id": "earth_boulder_run",
        "display_name": "Boulder Run",
        "objective_kind": "combat",
        "combat_pressure": "mid_high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="immediate",
            objective_label="Boulder Run",
        ),
        "notes": "Boulders crash in from one wall, rolling straight down lanes — weave between drops to reach the exit.",
    },
    {
        "room_id": "earth_shrine_circle",
        "display_name": "Shrine Circle",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "high",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "branch",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Stand on the shrine glyph to weaken enemies; step off and they regain power.",
    },
    # ── Earth biome mini-boss arena ────────────────────
    # Finale-eligible Golem encounter, gated to mud_caverns at depth >= 2
    # (level 3+).  Stays disabled until the boss controller, Golem enemy,
    # and armor-drop loop land in subsequent slices; at that point the
    # mud_caverns override flips it on.
    {
        "room_id": "earth_golem_arena",
        "display_name": "Stone Golem Arena",
        "objective_kind": "combat",
        "combat_pressure": "high",
        "decision_complexity": "mid",
        "topology_role": "finale",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 3,
        "path_stage_max": 4,
        "terminal_preference": "prefer",
        "repeat_cooldown": 0,
        "reward_affinity": "main",
        **_plan_shape(
            objective_rule="clear_enemies",
            guaranteed_chest=True,
            objective_label="Stone Golem",
        ),
        "notes": "A sealed arena where a Stone Golem mini-boss summons shard waves at HP thresholds; defeat it to unseal the exit portal and earn rare armor drops.",
    },
    # ── Biome-room expansion: Water (Sunken Ruins) ────────────────────
    # Phase 0 scaffold — templates registered with enabled=0 so they stay
    # out of generation until each is implemented in subsequent slices,
    # mirroring the Earth (mud_caverns) rollout.
    {
        "room_id": "water_river_room",
        "display_name": "River Room",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
            terrain_patch_count_range="3,5",
            terrain_patch_size_range="2,3",
        ),
        "notes": "A snaking river of CURRENT tiles cuts through the room; the flow speeds movement with it and resists movement against it.",
    },
    {
        "room_id": "water_waterfall_room",
        "display_name": "Waterfall Room",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "branch",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "branch",
        **_plan_shape(
            objective_rule="clear_enemies",
            guaranteed_chest=True,
        ),
        "notes": "A vertical band of falling current with a pool at its base; a chest hides inside the cascade and a stationary water spirit guards the pool.",
    },
    {
        "room_id": "water_spirit_room",
        "display_name": "Water Spirit Room",
        "objective_kind": "combat",
        "combat_pressure": "mid_high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(
            objective_rule="clear_enemies",
        ),
        "notes": "Stationary, invulnerable water spirits perched in pools fire water projectiles; clear the mortal enemies and slip past the spirits to the exit.",
    },
    # ── Water biome mini-boss arena ────────────────────
    {
        "room_id": "water_tide_lord_arena",
        "display_name": "Tide Lord Arena",
        "objective_kind": "combat",
        "combat_pressure": "high",
        "decision_complexity": "mid",
        "topology_role": "finale",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 3,
        "path_stage_max": 4,
        "terminal_preference": "prefer",
        "repeat_cooldown": 0,
        "reward_affinity": "main",
        **_plan_shape(
            objective_rule="clear_enemies",
            guaranteed_chest=True,
            objective_label="Tide Lord",
        ),
        "notes": "A flooded arena where a Tide Lord mini-boss summons spirit waves at HP thresholds; defeat it to unseal the exit portal and earn rare armor drops.",
    },
    # ── Ice biome terrain rooms ─────────────────────────
    {
        "room_id": "ice_thin_ice_field",
        "display_name": "Thin Ice Field",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "low",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(objective_rule="immediate"),
        "notes": "A chamber of cracking ice tiles that collapse into lethal pits after a few steps; safe floor corridors connect the doors to the room centre.",
    },
    {
        "room_id": "ice_crystal_room",
        "display_name": "Crystal Freeze Chamber",
        "objective_kind": "combat",
        "combat_pressure": "mid_high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(objective_rule="clear_enemies"),
        "notes": "Ice-slicked floor with immortal crystal pillars that periodically emit freeze pulses; getting caught in range of a pulse locks the player in place for a moment.",
    },
    {
        "room_id": "ice_freeze_aura_room",
        "display_name": "Aura Crystal Chamber",
        "objective_kind": "combat",
        "combat_pressure": "mid",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(objective_rule="clear_enemies"),
        "notes": "Immortal FreezeAuraCrystal fixtures pulse expanding aura rings; standing inside builds chill toward FROZEN.",
    },
    {
        "room_id": "ice_spirit_swarm_room",
        "display_name": "Spirit Swarm",
        "objective_kind": "combat",
        "combat_pressure": "high",
        "decision_complexity": "mid",
        "topology_role": "mid_run",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 2,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 1,
        "reward_affinity": "any",
        **_plan_shape(objective_rule="clear_enemies"),
        "notes": "A swarm of IceSpirit enemies dart at the player, apply chill on contact, and leave TRAIL_FREEZE tiles that collapse after a few seconds.",
    },
    {
        "room_id": "ice_avalanche_run",
        "display_name": "Ice Avalanche Run",
        "objective_kind": "traversal",
        "combat_pressure": "mid_high",
        "decision_complexity": "low",
        "topology_role": "mid_run",
        "min_depth": 1,
        "max_depth": None,
        "branch_preference": "linear",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 1,
        "path_stage_max": 4,
        "terminal_preference": "avoid",
        "repeat_cooldown": 2,
        "reward_affinity": "any",
        **_plan_shape(objective_rule="reach_exit"),
        "notes": "5-row SLIDE/boulder-lane layout; rolling ice boulders cross boulder lanes while SLIDE lanes commit the player's direction; two shatterable IcePillar cover objects.",
    },
    # ── Ice biome mini-boss arena ────────────────────────────────────────
    {
        "room_id": "ice_frost_witch_arena",
        "display_name": "Frost Witch Lair",
        "objective_kind": "combat",
        "combat_pressure": "high",
        "decision_complexity": "mid",
        "topology_role": "finale",
        "min_depth": 2,
        "max_depth": None,
        "branch_preference": "either",
        "generation_weight": 0,
        "enabled": 0,
        "implementation_status": "prototype",
        "objective_variant": "",
        "path_stage_min": 3,
        "path_stage_max": 4,
        "terminal_preference": "prefer",
        "repeat_cooldown": 0,
        "reward_affinity": "main",
        **_plan_shape(
            objective_rule="clear_enemies",
            guaranteed_chest=True,
            objective_label="Frost Witch",
        ),
        "notes": "A frozen lair where a Frost Witch mini-boss unleashes cone shards, nova frost bursts, and phase-2 lunges while summoning IceSpirit waves at HP thresholds; defeat her to unseal the portal.",
    },
)


def _override_template(room_id, **updates):
    base = next(template for template in BASE_ROOM_TEMPLATES if template["room_id"] == room_id)
    overridden = dict(base)
    overridden.update(updates)
    return overridden


DUNGEON_ROOM_TEMPLATE_OVERRIDES = {
    "mud_caverns": (
        _override_template(
            "escort_protection",
            display_name="Shrine Pilgrim Escort",
            objective_label="Pilgrim",
            objective_max_hp=28,
            objective_move_speed=1.15,
            objective_guide_radius=96,
            objective_damage_cooldown_ms=450,
            notes="Guide the shrine pilgrim through collapsing earth lanes before the cavern seals behind them.",
        ),
        _override_template(
            "escort_bomb_carrier",
            display_name="Powder Cart Push",
            objective_label="Sapper",
            objective_max_hp=32,
            objective_move_speed=0.95,
            objective_guide_radius=88,
            objective_exit_radius=22,
            objective_damage_cooldown_ms=550,
            notes="Protect the sapper pushing unstable powder charges through boulder-strewn corridors.",
        ),
        _override_template(
            "survival_holdout",
            display_name="Shrine Ring Stand",
            objective_label="Shrine",
            holdout_zone_radius=88,
            scripted_wave_sizes="1,2,2",
            holdout_relief_count=1,
            holdout_relief_delay_ms=1400,
            notes="Hold the shrine ring while stabilizers buy breathing room against the cave-in pressure.",
        ),
        _override_template(
            "resource_race",
            display_name="Heartstone Claim",
            objective_variant="heartstone_shard",
            objective_duration_ms=6800,
            scripted_wave_sizes="1,2,2",
            notes="Reach the heartstone before rival claimants lock the quarry down around it.",
        ),
        _override_template(
            "trap_gauntlet",
            display_name="Boulder Sweep Run",
            objective_variant="sweeper_lanes",
            trap_intensity_scale=1.4,
            trap_speed_scale=0.85,
            trap_challenge_reward_kind="stat_shard",
            notes="Thread through moving stone sweepers, or risk the challenge lane for a better cache. The boulders hit heavy and roll a touch slower, so a single brush off the safe lane can shred low-armor builds. Bonus route grants a stat shard.",
        ),
        _override_template(
            "stealth_passage",
            display_name="Quicksand Ward Path",
            objective_variant="release_on_alarm",
            objective_label="Shrine",
            objective_layout_offsets="-5,-2;5,-2;0,4",
            objective_patrol_offset="0,2",
            objective_patrol_shape="rect",
            objective_radius=38,
            objective_duration_ms=2400,
            notes="Slip between buried shrine wards before the quicksand search phase escalates into a cave lockdown.",
        ),
        _override_template(
            "puzzle_gated_doors",
            display_name="Rune Lock Gallery",
            objective_variant="ordered_plates",
            objective_label="Rune",
            puzzle_reinforcement_count=1,
            puzzle_stall_duration_ms=3000,
            puzzle_stabilizer_count=1,
            puzzle_stabilizer_hp=10,
            puzzle_camp_pulse_damage=1,
            puzzle_camp_pulse_interval_ms=1100,
            puzzle_camp_pulse_grace_ms=1200,
            puzzle_camp_pulse_radius=38,
            notes="Follow the numbered rune order while cave-in dust pulses solved glyphs, or shatter the crumbling buried glyph to skip a step.",
        ),
        _override_template(
            "ritual_disruption",
            display_name="Spore Totem Grove",
            objective_variant="spore_totem",
            ritual_link_mode="role_chain",
            ritual_wrong_strike_spawn_count=1,
            generation_weight=4,
            notes="Destroy spore totems in script order — summoners first, then pulse heads, then wards — while fungal pulse rings punish camping. Striking a shielded totem releases a spore swarm.",
        ),
        _override_template(
            "timed_extraction",
            display_name="Mire Cache Extraction",
            objective_variant="mire_cache",
            scripted_wave_sizes="1,2,2",
            notes="Secure the mire cache, then push out before the marsh closes in.",
        ),
        # Biome-only earth rooms (Phase 2 of biome room expansion).
        _override_template(
            "earth_stalagmite_field",
            enabled=1,
            generation_weight=2,
            notes="Stalagmite spines studding the cavern floor tick damage on contact.",
        ),
        _override_template(
            "earth_quicksand_trap",
            enabled=1,
            generation_weight=2,
            notes="Quicksand pools drag careless adventurers under within seconds.",
        ),
        _override_template(
            "earth_crystal_vein",
            enabled=1,
            generation_weight=2,
            notes="Buff-bearing crystals nestle among the cavern enemies.",
        ),
        _override_template(
            "earth_tremor_chamber",
            enabled=1,
            generation_weight=1,
            notes="Cavern tremors hammer everyone outside the hearth circles.",
        ),
        _override_template(
            "earth_mushroom_grove",
            enabled=1,
            generation_weight=2,
            notes="Spore mushrooms exhale poison rings between waves.",
        ),
        _override_template(
            "earth_cave_in",
            enabled=1,
            generation_weight=1,
            notes="Telegraphed collapses turn the cavern floor into lethal pits.",
        ),
        _override_template(
            "earth_mining_carts",
            enabled=1,
            generation_weight=1,
            notes="Auto-rolling carts thunder down rail rows on a strict cycle.",
        ),
        _override_template(
            "earth_burrower_den",
            enabled=1,
            generation_weight=1,
            notes="Burrowing creatures erupt from telegraphed mounds during combat.",
        ),
        _override_template(
            "earth_echo_cavern",
            enabled=1,
            generation_weight=1,
            notes="A claustrophobic cave where vision is squeezed to a narrow ring.",
        ),
        _override_template(
            "earth_boulder_run",
            enabled=1,
            generation_weight=1,
            notes="Massive boulders roll across the cavern in telegraphed waves.",
        ),
        _override_template(
            "earth_shrine_circle",
            enabled=1,
            generation_weight=1,
            notes="An ancient shrine weakens nearby foes — but only while you stand within its circle.",
        ),
        _override_template(
            "earth_golem_arena",
            enabled=1,
            generation_weight=1,
            notes="A Stone Golem stalks a sealed arena, summoning shard reinforcements at each HP threshold; only its defeat opens the portal.",
        ),
    ),
    "frozen_depths": (
        _override_template(
            "escort_protection",
            display_name="Icebound Archivist Escort",
            objective_label="Archivist",
            objective_max_hp=24,
            objective_move_speed=1.3,
            objective_guide_radius=100,
            objective_exit_radius=22,
            objective_damage_cooldown_ms=450,
            notes="Keep the archivist moving across brittle ice lanes before whiteout hunters close in.",
        ),
        _override_template(
            "escort_bomb_carrier",
            display_name="Frost Charge Run",
            objective_label="Saboteur",
            objective_max_hp=28,
            objective_move_speed=1.05,
            objective_guide_radius=100,
            objective_exit_radius=22,
            objective_damage_cooldown_ms=500,
            notes="Cover the saboteur carrying frost charges through exposed ice corridors.",
        ),
        _override_template(
            "survival_holdout",
            display_name="Crystal Beacon Hold",
            objective_label="Beacon",
            holdout_zone_radius=104,
            scripted_wave_sizes="1,2,2",
            holdout_relief_count=2,
            holdout_relief_delay_ms=1200,
            notes="Hold the crystal beacon while stabilizers cut through whiteout pressure for a moment.",
        ),
        _override_template(
            "resource_race",
            display_name="Glacier Core Claim",
            objective_variant="glacier_core",
            objective_duration_ms=7200,
            scripted_wave_sizes="1,1,2",
            notes="Secure the glacier core before icebound claimants and frost wards seal the chamber.",
        ),
        _override_template(
            "trap_gauntlet",
            display_name="Frost Vent Gauntlet",
            objective_variant="vent_lanes",
            objective_label="Vent Switch",
            trap_intensity_scale=0.8,
            trap_speed_scale=1.25,
            trap_challenge_reward_kind="tempo_rune",
            notes="Use the switches to quiet one frost-vent lane, or take the challenge route for better loot. Vents jet quickly and bite a little less than the boulder run, rewarding precise timing over heavy armor. Bonus route grants a tempo rune.",
        ),
        _override_template(
            "stealth_passage",
            display_name="Whiteout Watch",
            objective_variant="escape_on_alarm",
            objective_label="Crystal",
            objective_layout_offsets="-5,-1;5,-1;0,5",
            objective_patrol_offset="2,0",
            objective_patrol_shape="zigzag",
            objective_radius=40,
            objective_duration_ms=2600,
            notes="Cross the whiteout under crystal watchposts before the search phase hardens into lockdown.",
        ),
        _override_template(
            "puzzle_gated_doors",
            display_name="Mirror Rune Gallery",
            objective_variant="paired_runes",
            objective_label="Rune",
            objective_entity_count=4,
            puzzle_reinforcement_count=2,
            puzzle_stall_duration_ms=1800,
            puzzle_stabilizer_count=1,
            puzzle_stabilizer_hp=12,
            puzzle_camp_pulse_damage=1,
            puzzle_camp_pulse_interval_ms=1200,
            puzzle_camp_pulse_grace_ms=1100,
            puzzle_camp_pulse_radius=36,
            notes="Match rune pairs in the right sequence while solved mirrors radiate frostbite, or shatter the optional stabilizer to skip an entire pair.",
        ),
        _override_template(
            "ritual_disruption",
            display_name="Frost Obelisk Break",
            objective_variant="frost_obelisk",
            ritual_link_mode="pulse_gates_damage",
            generation_weight=4,
            notes="Shatter frost obelisks during their pulse windows while cold bursts punish stationary play.",
        ),
        _override_template(
            "timed_extraction",
            display_name="Reliquary Extraction",
            objective_variant="glacier_reliquary",
            scripted_wave_sizes="1,2,3",
            notes="Claim the reliquary and escape before reinforcements lock the ice lanes.",
        ),
        _override_template(
            "ice_thin_ice_field",
            enabled=1,
            generation_weight=2,
            terrain_type="ice",
            notes="Cracking ice floor with BFS-carved safe corridors; tiles collapse after repeated steps.",
        ),
        _override_template(
            "ice_crystal_room",
            enabled=1,
            generation_weight=2,
            terrain_type="ice",
            notes="Ice-slicked floor with immortal crystal pillars that pulse freeze on nearby targets.",
        ),
        _override_template(
            "ice_freeze_aura_room",
            enabled=1,
            generation_weight=2,
            terrain_type="ice",
            notes="FreezeAuraCrystal fixtures pulse chill-building aura rings; defeat the enemy cohort while avoiding aura exposure.",
        ),
        _override_template(
            "ice_spirit_swarm_room",
            enabled=1,
            generation_weight=2,
            terrain_type="ice",
            notes="IceSpirit swarm; contact builds chill and leaves TRAIL_FREEZE tiles that collapse after TRAIL_FREEZE_DURATION_MS.",
        ),
        _override_template(
            "ice_avalanche_run",
            enabled=1,
            generation_weight=2,
            terrain_type="ice",
            notes="Horizontal boulder-lane run on SLIDE tiles; two IcePillar cover objects provide temporary shelter.",
        ),
        _override_template(
            "ice_frost_witch_arena",
            enabled=1,
            generation_weight=1,
            terrain_type="ice",
            notes="Frost Witch boss arena: THIN_ICE disc + SLIDE ring; cone shards, nova bursts, and phase-2 lunges; IceSpirit waves at HP thresholds.",
        ),
    ),
    "sunken_ruins": (
        _override_template(
            "escort_protection",
            display_name="River Guide Escort",
            objective_label="Guide",
            objective_max_hp=27,
            objective_move_speed=1.25,
            objective_guide_radius=104,
            objective_exit_radius=24,
            objective_damage_cooldown_ms=450,
            notes="Protect the river guide while they lead you through flooded channels and shifting currents.",
        ),
        _override_template(
            "escort_bomb_carrier",
            display_name="Flood Charge Run",
            objective_label="Diver",
            objective_max_hp=29,
            objective_move_speed=1.0,
            objective_guide_radius=102,
            objective_exit_radius=24,
            objective_damage_cooldown_ms=500,
            notes="Escort the diver carrying flood charges past submerged ambush lanes.",
        ),
        _override_template(
            "survival_holdout",
            display_name="Tide Beacon Hold",
            objective_label="Beacon",
            holdout_zone_radius=100,
            scripted_wave_sizes="1,2,3",
            holdout_relief_count=2,
            holdout_relief_delay_ms=1300,
            notes="Hold the tide beacon while stabilizers blunt the next flood surge for a moment.",
        ),
        _override_template(
            "resource_race",
            display_name="Pearl Claim",
            objective_variant="tide_pearl",
            objective_duration_ms=6600,
            scripted_wave_sizes="1,2,3",
            notes="Secure the tide pearl before the chamber fills with rival divers and flood pressure.",
        ),
        _override_template(
            "trap_gauntlet",
            display_name="Floodgate Hazard Run",
            objective_variant="mixed_lanes",
            trap_intensity_scale=1.15,
            trap_challenge_reward_kind="mobility_consumable",
            notes="Use the entry and checkpoint switches to reroute through a mixed floodgate gauntlet of sweepers, vents, and crushers, then commit to the challenge lane for the vault cache. The flood-charged hazards hit harder than the standard set.",
        ),
        _override_template(
            "stealth_passage",
            display_name="Tide Watch Passage",
            objective_variant="escape_on_alarm",
            objective_label="Watcher",
            objective_layout_offsets="-4,-3;4,-3;0,3",
            objective_patrol_offset="1,-2",
            objective_patrol_shape="rect",
            objective_radius=36,
            objective_duration_ms=2100,
            notes="Slip past tide watchers before the search phase gives way to a flooded lockdown.",
        ),
        _override_template(
            "puzzle_gated_doors",
            display_name="Tidal Counter-Seals",
            objective_variant="staggered_plates",
            objective_label="Glyph",
            objective_entity_count=4,
            puzzle_reinforcement_count=2,
            puzzle_stall_duration_ms=2200,
            puzzle_stabilizer_count=1,
            puzzle_stabilizer_hp=12,
            puzzle_camp_pulse_damage=2,
            puzzle_camp_pulse_interval_ms=900,
            puzzle_camp_pulse_grace_ms=900,
            puzzle_camp_pulse_radius=42,
            notes="Follow the staggered tidal glyph order, or shatter the optional stabilizer to skip a glyph while waves punish resets and solved seals tide-pulse anyone lingering on them.",
        ),
        _override_template(
            "ritual_disruption",
            display_name="Tidal Idol Collapse",
            objective_variant="tidal_idol",
            generation_weight=4,
            notes="Break tidal idols while wave pulses pressure the player out of the center.",
        ),
        _override_template(
            "timed_extraction",
            display_name="Sarcophagus Extraction",
            objective_variant="sunken_sarcophagus",
            scripted_wave_sizes="1,2,3",
            notes="Secure the sarcophagus and escape before the chamber floods with enemies.",
        ),
        # Biome-only water rooms.
        _override_template(
            "water_river_room",
            enabled=1,
            generation_weight=2,
            notes="A river of CURRENT tiles slices the chamber; ride it for speed or push against it to cross.",
        ),
        _override_template(
            "water_waterfall_room",
            enabled=1,
            generation_weight=2,
            notes="A vertical CURRENT cascade pours into a WATER pool; a chest hides at the top of the falls, reachable only by pushing up against the flow.",
        ),
        _override_template(
            "water_spirit_room",
            enabled=1,
            generation_weight=2,
            notes="Invulnerable water spirits guard WATER pools scattered across the chamber; clear the room objective to open the portal.",
        ),
        _override_template(
            "water_tide_lord_arena",
            enabled=1,
            generation_weight=1,
            notes="Flooded arena where the Tide Lord mini-boss fires wave surges and summons spirit adds at HP thresholds; defeat it for rare armor drops.",
        ),
    ),
}


def _room_template_table_sql(table_name):
    return f"""
CREATE TABLE IF NOT EXISTS {table_name} (
    room_id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    objective_kind TEXT NOT NULL,
    combat_pressure TEXT NOT NULL,
    decision_complexity TEXT NOT NULL,
    topology_role TEXT NOT NULL,
    min_depth INTEGER NOT NULL DEFAULT 0,
    max_depth INTEGER,
    branch_preference TEXT NOT NULL DEFAULT 'either',
    generation_weight INTEGER NOT NULL DEFAULT 1,
    enabled INTEGER NOT NULL DEFAULT 1,
    implementation_status TEXT NOT NULL DEFAULT 'planned',
    objective_variant TEXT NOT NULL DEFAULT '',
    path_stage_min INTEGER NOT NULL DEFAULT 0,
    path_stage_max INTEGER NOT NULL DEFAULT 4,
    terminal_preference TEXT NOT NULL DEFAULT 'any',
    repeat_cooldown INTEGER NOT NULL DEFAULT 0,
    reward_affinity TEXT NOT NULL DEFAULT 'any',
    objective_rule TEXT NOT NULL DEFAULT 'immediate',
    objective_duration_ms INTEGER,
    enemy_minimum_bonus INTEGER NOT NULL DEFAULT 0,
    enemy_scale_factor REAL NOT NULL DEFAULT 1.0,
    guaranteed_chest INTEGER NOT NULL DEFAULT 0,
    chest_spawn_chance REAL,
    terrain_patch_count_range TEXT NOT NULL DEFAULT '',
    terrain_patch_size_range TEXT NOT NULL DEFAULT '',
    clear_center INTEGER NOT NULL DEFAULT 0,
    terminal_chest_lock INTEGER NOT NULL DEFAULT 0,
    objective_entity_count INTEGER NOT NULL DEFAULT 0,
    scripted_wave_sizes TEXT NOT NULL DEFAULT '',
    holdout_zone_radius INTEGER NOT NULL DEFAULT 0,
    holdout_zone_min_radius INTEGER NOT NULL DEFAULT 0,
    holdout_zone_shrink_ms INTEGER NOT NULL DEFAULT 0,
    holdout_zone_migrate_ms INTEGER NOT NULL DEFAULT 0,
    holdout_zone_migration_offsets TEXT NOT NULL DEFAULT '',
    holdout_relief_count INTEGER NOT NULL DEFAULT 0,
    holdout_relief_delay_ms INTEGER NOT NULL DEFAULT 0,
    holdout_stabilizer_migration_delay_ms INTEGER NOT NULL DEFAULT 0,
    ritual_role_script TEXT NOT NULL DEFAULT '',
    ritual_reinforcement_count INTEGER NOT NULL DEFAULT 0,
    ritual_link_mode TEXT NOT NULL DEFAULT '',
    ritual_payoff_kind TEXT NOT NULL DEFAULT '',
    ritual_payoff_label TEXT NOT NULL DEFAULT '',
    ritual_wrong_strike_spawn_count INTEGER NOT NULL DEFAULT 0,
    objective_label TEXT NOT NULL DEFAULT '',
    objective_layout_offsets TEXT NOT NULL DEFAULT '',
    objective_spawn_offset TEXT NOT NULL DEFAULT '',
    objective_patrol_offset TEXT NOT NULL DEFAULT '',
    objective_patrol_shape TEXT NOT NULL DEFAULT 'line',
    objective_radius INTEGER NOT NULL DEFAULT 0,
    objective_trigger_padding INTEGER NOT NULL DEFAULT 0,
    objective_max_hp INTEGER NOT NULL DEFAULT 0,
    objective_move_speed REAL NOT NULL DEFAULT 0.0,
    objective_guide_radius INTEGER NOT NULL DEFAULT 0,
    objective_exit_radius INTEGER NOT NULL DEFAULT 0,
    objective_damage_cooldown_ms INTEGER NOT NULL DEFAULT 0,
    puzzle_reinforcement_count INTEGER NOT NULL DEFAULT 0,
    puzzle_stall_duration_ms INTEGER NOT NULL DEFAULT 0,
    puzzle_stabilizer_count INTEGER NOT NULL DEFAULT 0,
    puzzle_stabilizer_hp INTEGER NOT NULL DEFAULT 0,
    puzzle_camp_pulse_damage INTEGER NOT NULL DEFAULT 0,
    puzzle_camp_pulse_interval_ms INTEGER NOT NULL DEFAULT 0,
    puzzle_camp_pulse_grace_ms INTEGER NOT NULL DEFAULT 0,
    puzzle_camp_pulse_radius INTEGER NOT NULL DEFAULT 0,
    trap_intensity_scale REAL NOT NULL DEFAULT 1.0,
    trap_speed_scale REAL NOT NULL DEFAULT 1.0,
    trap_challenge_reward_kind TEXT NOT NULL DEFAULT 'chest_upgrade',
    notes TEXT NOT NULL DEFAULT ''
);
"""


_SCHEMA = "\n".join(
    [
        _room_template_table_sql(BASE_ROOM_TEMPLATE_TABLE),
        *[
            _room_template_table_sql(table_name)
            for table_name in DUNGEON_ROOM_TEMPLATE_TABLES.values()
        ],
    ]
)


def _get_conn():
    conn = sqlite3.connect(_DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.executescript(_SCHEMA)
    _ensure_schema_columns(conn)
    return conn


def ensure_room_content_db():
    """Create the room-content database and seed shared templates."""
    conn = _get_conn()
    try:
        _seed_base_room_templates(conn)
        _seed_dungeon_room_templates(conn)
        conn.commit()
    finally:
        conn.close()


def get_dungeon_room_template_table(dungeon_id):
    """Return the dungeon-specific room-template table name for a dungeon."""
    return DUNGEON_ROOM_TEMPLATE_TABLES[dungeon_id]


def load_room_catalog(dungeon_id):
    """Return the merged base and dungeon-specific room catalog."""
    ensure_room_content_db()

    conn = _get_conn()
    try:
        templates = {
            template["room_id"]: template
            for template in _fetch_room_templates(conn, BASE_ROOM_TEMPLATE_TABLE)
        }
        for template in _fetch_room_templates(
            conn, get_dungeon_room_template_table(dungeon_id)
        ):
            templates[template["room_id"]] = template
        return tuple(templates[key] for key in sorted(templates))
    finally:
        conn.close()


def _fetch_room_templates(conn, table_name):
    rows = conn.execute(
        f"SELECT {', '.join(ROOM_TEMPLATE_COLUMNS)} FROM {table_name} ORDER BY room_id"
    ).fetchall()
    return tuple(dict(row) for row in rows)


def _seed_base_room_templates(conn):
    column_list = ", ".join(ROOM_TEMPLATE_COLUMNS)
    placeholders = ", ".join("?" for _ in ROOM_TEMPLATE_COLUMNS)
    update_clause = ", ".join(
        f"{column}=excluded.{column}" for column in ROOM_TEMPLATE_COLUMNS[1:]
    )

    for template in BASE_ROOM_TEMPLATES:
        values = tuple(template[column] for column in ROOM_TEMPLATE_COLUMNS)
        conn.execute(
            f"INSERT INTO {BASE_ROOM_TEMPLATE_TABLE} ({column_list}) "
            f"VALUES ({placeholders}) "
            f"ON CONFLICT(room_id) DO UPDATE SET {update_clause}",
            values,
        )


def _seed_dungeon_room_templates(conn):
    column_list = ", ".join(ROOM_TEMPLATE_COLUMNS)
    placeholders = ", ".join("?" for _ in ROOM_TEMPLATE_COLUMNS)
    update_clause = ", ".join(
        f"{column}=excluded.{column}" for column in ROOM_TEMPLATE_COLUMNS[1:]
    )

    for dungeon_id, templates in DUNGEON_ROOM_TEMPLATE_OVERRIDES.items():
        table_name = get_dungeon_room_template_table(dungeon_id)
        for template in templates:
            values = tuple(template[column] for column in ROOM_TEMPLATE_COLUMNS)
            conn.execute(
                f"INSERT INTO {table_name} ({column_list}) "
                f"VALUES ({placeholders}) "
                f"ON CONFLICT(room_id) DO UPDATE SET {update_clause}",
                values,
            )


def _ensure_schema_columns(conn):
    missing_column_defaults = {
        "objective_variant": "TEXT NOT NULL DEFAULT ''",
        "path_stage_min": "INTEGER NOT NULL DEFAULT 0",
        "path_stage_max": "INTEGER NOT NULL DEFAULT 4",
        "terminal_preference": "TEXT NOT NULL DEFAULT 'any'",
        "repeat_cooldown": "INTEGER NOT NULL DEFAULT 0",
        "reward_affinity": "TEXT NOT NULL DEFAULT 'any'",
        "objective_rule": "TEXT NOT NULL DEFAULT 'immediate'",
        "objective_duration_ms": "INTEGER",
        "enemy_minimum_bonus": "INTEGER NOT NULL DEFAULT 0",
        "enemy_scale_factor": "REAL NOT NULL DEFAULT 1.0",
        "guaranteed_chest": "INTEGER NOT NULL DEFAULT 0",
        "chest_spawn_chance": "REAL",
        "terrain_patch_count_range": "TEXT NOT NULL DEFAULT ''",
        "terrain_patch_size_range": "TEXT NOT NULL DEFAULT ''",
        "clear_center": "INTEGER NOT NULL DEFAULT 0",
        "terminal_chest_lock": "INTEGER NOT NULL DEFAULT 0",
        "objective_entity_count": "INTEGER NOT NULL DEFAULT 0",
        "scripted_wave_sizes": "TEXT NOT NULL DEFAULT ''",
        "holdout_zone_radius": "INTEGER NOT NULL DEFAULT 0",
        "holdout_zone_min_radius": "INTEGER NOT NULL DEFAULT 0",
        "holdout_zone_shrink_ms": "INTEGER NOT NULL DEFAULT 0",
        "holdout_zone_migrate_ms": "INTEGER NOT NULL DEFAULT 0",
        "holdout_zone_migration_offsets": "TEXT NOT NULL DEFAULT ''",
        "holdout_relief_count": "INTEGER NOT NULL DEFAULT 0",
        "holdout_relief_delay_ms": "INTEGER NOT NULL DEFAULT 0",
        "holdout_stabilizer_migration_delay_ms": "INTEGER NOT NULL DEFAULT 0",
        "ritual_role_script": "TEXT NOT NULL DEFAULT ''",
        "ritual_reinforcement_count": "INTEGER NOT NULL DEFAULT 0",
        "ritual_link_mode": "TEXT NOT NULL DEFAULT ''",
        "ritual_payoff_kind": "TEXT NOT NULL DEFAULT ''",
        "ritual_payoff_label": "TEXT NOT NULL DEFAULT ''",
        "ritual_wrong_strike_spawn_count": "INTEGER NOT NULL DEFAULT 0",
        "objective_label": "TEXT NOT NULL DEFAULT ''",
        "objective_layout_offsets": "TEXT NOT NULL DEFAULT ''",
        "objective_spawn_offset": "TEXT NOT NULL DEFAULT ''",
        "objective_patrol_offset": "TEXT NOT NULL DEFAULT ''",
        "objective_patrol_shape": "TEXT NOT NULL DEFAULT 'line'",
        "objective_radius": "INTEGER NOT NULL DEFAULT 0",
        "objective_trigger_padding": "INTEGER NOT NULL DEFAULT 0",
        "objective_max_hp": "INTEGER NOT NULL DEFAULT 0",
        "objective_move_speed": "REAL NOT NULL DEFAULT 0.0",
        "objective_guide_radius": "INTEGER NOT NULL DEFAULT 0",
        "objective_exit_radius": "INTEGER NOT NULL DEFAULT 0",
        "objective_damage_cooldown_ms": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_reinforcement_count": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_stall_duration_ms": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_stabilizer_count": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_stabilizer_hp": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_camp_pulse_damage": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_camp_pulse_interval_ms": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_camp_pulse_grace_ms": "INTEGER NOT NULL DEFAULT 0",
        "puzzle_camp_pulse_radius": "INTEGER NOT NULL DEFAULT 0",
        "trap_intensity_scale": "REAL NOT NULL DEFAULT 1.0",
        "trap_speed_scale": "REAL NOT NULL DEFAULT 1.0",
        "trap_challenge_reward_kind": "TEXT NOT NULL DEFAULT 'chest_upgrade'",
    }
    for table_name in (BASE_ROOM_TEMPLATE_TABLE, *DUNGEON_ROOM_TEMPLATE_TABLES.values()):
        existing = {
            row[1]
            for row in conn.execute(f"PRAGMA table_info({table_name})").fetchall()
        }
        for column_name, column_def in missing_column_defaults.items():
            if column_name in existing:
                continue
            conn.execute(
                f"ALTER TABLE {table_name} ADD COLUMN {column_name} {column_def}"
            )