"""Static item definitions, loadout metadata, and loot tables."""

from settings import (
    HEAL_SMALL, HEAL_MEDIUM, HEAL_LARGE,
    POTION_SMALL_MAX, POTION_MEDIUM_MAX, POTION_LARGE_MAX,
    SPEED_BOOST_MAX, ATTACK_BOOST_MAX, COMPASS_MAX,
    SPARK_CHARGE_MAX,
    LOOT_WEIGHT_SPARK_CHARGE, CHEST_LOOT_WEIGHT_SPARK_CHARGE,
    ARMOR_HP, COMPASS_USES,
    PRICE_POTION_SMALL, PRICE_POTION_MEDIUM, PRICE_POTION_LARGE,
    PRICE_SPEED_BOOST, PRICE_ATTACK_BOOST, PRICE_ARMOR,
    PRICE_WEAPON_PLUS, PRICE_COMPASS,
    COLOR_HEALTH_POTION, COLOR_SPEED_BOOST,
    COLOR_ARMOR, COLOR_COMPASS,
    LOOT_WEIGHT_POTION_SMALL, LOOT_WEIGHT_POTION_MEDIUM,
    LOOT_WEIGHT_POTION_LARGE, LOOT_WEIGHT_SPEED_BOOST,
    LOOT_WEIGHT_ATTACK_BOOST,
    CHEST_LOOT_WEIGHT_POTION_SMALL, CHEST_LOOT_WEIGHT_POTION_MEDIUM,
    CHEST_LOOT_WEIGHT_POTION_LARGE, CHEST_LOOT_WEIGHT_SPEED_BOOST,
    CHEST_LOOT_WEIGHT_ATTACK_BOOST,
    RARITY_COMMON, RARITY_UNCOMMON, RARITY_RARE,
    RARITY_SUPERIOR, RARITY_EXQUISITE, RARITY_EXOTIC, RARITY_LEGENDARY,
    RARITY_TIERS, RARITY_COLORS,
)


EQUIPMENT_SLOTS = (
    "weapon_1",
    "weapon_2",
    "helmet",
    "chest",
    "arms",
    "legs",
    "ring_1",
    "ring_2",
    "ring_3",
    "ring_4",
    "pendant",
    "belt",
)
RING_EQUIPMENT_SLOTS = ("ring_1", "ring_2", "ring_3", "ring_4")
WEAPON_EQUIPMENT_SLOTS = ("weapon_1", "weapon_2")
STARTER_WEAPON_IDS = ("sword", "spear", "axe", "hammer")
UPGRADEABLE_WEAPON_IDS = STARTER_WEAPON_IDS
DEFAULT_EQUIPPED_SLOTS = {
    "weapon_1": "sword",
    "weapon_2": "spear",
    "helmet": None,
    "chest": None,
    "arms": None,
    "legs": None,
    "ring_1": None,
    "ring_2": None,
    "ring_3": None,
    "ring_4": None,
    "pendant": None,
    "belt": None,
}


ITEM_DATABASE = {
    "health_potion_small": {
        "name": "Small Health Potion",
        "description": f"Restores {HEAL_SMALL} HP",
        "cost": PRICE_POTION_SMALL,
        "icon_color": COLOR_HEALTH_POTION,
        "max_owned": POTION_SMALL_MAX,
        "can_purchase": True,
        "can_loot": True,
        "drop_weight": LOOT_WEIGHT_POTION_SMALL,
        "chest_drop_weight": CHEST_LOOT_WEIGHT_POTION_SMALL,
        "category": "potion",
        "rarity": RARITY_COMMON,
    },
    "health_potion_medium": {
        "name": "Medium Health Potion",
        "description": f"Restores {HEAL_MEDIUM} HP",
        "cost": PRICE_POTION_MEDIUM,
        "icon_color": (20, 160, 50),
        "max_owned": POTION_MEDIUM_MAX,
        "can_purchase": True,
        "can_loot": True,
        "drop_weight": LOOT_WEIGHT_POTION_MEDIUM,
        "chest_drop_weight": CHEST_LOOT_WEIGHT_POTION_MEDIUM,
        "category": "potion",
        "rarity": RARITY_UNCOMMON,
    },
    "health_potion_large": {
        "name": "Large Health Potion",
        "description": f"Restores {HEAL_LARGE} HP (full heal)",
        "cost": PRICE_POTION_LARGE,
        "icon_color": (10, 120, 40),
        "max_owned": POTION_LARGE_MAX,
        "can_purchase": True,
        "can_loot": True,
        "drop_weight": LOOT_WEIGHT_POTION_LARGE,
        "chest_drop_weight": CHEST_LOOT_WEIGHT_POTION_LARGE,
        "category": "potion",
        "rarity": RARITY_RARE,
    },
    "speed_boost": {
        "name": "Speed Boost",
        "description": "Doubles movement speed for 20s",
        "cost": PRICE_SPEED_BOOST,
        "icon_color": COLOR_SPEED_BOOST,
        "max_owned": SPEED_BOOST_MAX,
        "can_purchase": True,
        "can_loot": True,
        "drop_weight": LOOT_WEIGHT_SPEED_BOOST,
        "chest_drop_weight": CHEST_LOOT_WEIGHT_SPEED_BOOST,
        "category": "boost",
        "rarity": RARITY_COMMON,
    },
    "attack_boost": {
        "name": "Attack Boost",
        "description": "Doubles damage for 20s",
        "cost": PRICE_ATTACK_BOOST,
        "icon_color": (255, 80, 80),
        "max_owned": ATTACK_BOOST_MAX,
        "can_purchase": True,
        "can_loot": True,
        "drop_weight": LOOT_WEIGHT_ATTACK_BOOST,
        "chest_drop_weight": CHEST_LOOT_WEIGHT_ATTACK_BOOST,
        "category": "boost",
        "rarity": RARITY_UNCOMMON,
    },
    "spark_charge": {
        "name": "Spark Charge",
        "description": "Reduces dodge cooldown by 60% for 12s.",
        "cost": 25,
        "icon_color": (80, 200, 255),
        "max_owned": SPARK_CHARGE_MAX,
        "can_purchase": True,
        "can_loot": True,
        "drop_weight": LOOT_WEIGHT_SPARK_CHARGE,
        "chest_drop_weight": CHEST_LOOT_WEIGHT_SPARK_CHARGE,
        "category": "boost",
        "rarity": RARITY_UNCOMMON,
    },
    "armor": {
        "name": "Iron Chestplate",
        "description": "Iron chest armor. Absorbs incoming damage.",
        "cost": PRICE_ARMOR,
        "icon_color": COLOR_ARMOR,
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "rarity": RARITY_UNCOMMON,
        "theme_tag": "heavy",
    },
    "sword_plus": {
        "name": "+1 Sword",
        "description": "1.5x sword damage. Lost on death.",
        "cost": PRICE_WEAPON_PLUS,
        "icon_color": (220, 220, 255),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "weapon_upgrade",
        "rarity": RARITY_UNCOMMON,
    },
    "spear_plus": {
        "name": "+1 Spear",
        "description": "1.5x spear damage. Lost on death.",
        "cost": PRICE_WEAPON_PLUS,
        "icon_color": (200, 255, 200),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "weapon_upgrade",
        "rarity": RARITY_UNCOMMON,
    },
    "axe_plus": {
        "name": "+1 Axe",
        "description": "1.5x axe damage. Lost on death.",
        "cost": PRICE_WEAPON_PLUS,
        "icon_color": (255, 200, 200),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "weapon_upgrade",
        "rarity": RARITY_UNCOMMON,
    },
    "compass": {
        "name": "Compass",
        "description": f"Points toward portal ({COMPASS_USES} uses)",
        "cost": PRICE_COMPASS,
        "icon_color": COLOR_COMPASS,
        "max_owned": COMPASS_MAX,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "tool",
        "rarity": RARITY_UNCOMMON,
    },
}

ITEM_DATABASE.update({
    "sword": {
        "name": "Sword",
        "description": "Starter weapon. Slash damage.",
        "cost": 0,
        "icon_color": (220, 220, 255),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "weapon",
        "equipment_slots": list(WEAPON_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "weapon_id": "sword",
        "damage_type": "slash",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    "spear": {
        "name": "Spear",
        "description": "Starter weapon. Pierce damage.",
        "cost": 0,
        "icon_color": (200, 255, 200),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "weapon",
        "equipment_slots": list(WEAPON_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "weapon_id": "spear",
        "damage_type": "pierce",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    "axe": {
        "name": "Axe",
        "description": "Starter weapon. Slash damage.",
        "cost": 0,
        "icon_color": (255, 200, 200),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "weapon",
        "equipment_slots": list(WEAPON_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "weapon_id": "axe",
        "damage_type": "slash",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    "hammer": {
        "name": "Hammer",
        "description": "Starter weapon. Blunt damage.",
        "cost": 0,
        "icon_color": (180, 180, 180),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "weapon",
        "equipment_slots": list(WEAPON_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "weapon_id": "hammer",
        "damage_type": "blunt",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    # ── Hunter exclusive weapons (Danger Mode drops) ────────────────────
    "hunter_heavy_blade": {
        "name": "Hunter's Heavy Blade",
        "description": "Slow but devastating cleave. Drops from the Hunter.",
        "cost": 0,
        "icon_color": (180, 20, 20),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": True,
        "drop_weight": 0,
        "category": "weapon",
        "equipment_slots": list(WEAPON_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "weapon_id": "hunter_heavy_blade",
        "damage_type": "slash",
        "is_equippable": True,
        "rarity": RARITY_RARE,
    },
    "hunter_spectral_bow": {
        "name": "Hunter's Spectral Bow",
        "description": "Fires a piercing bolt through all enemies. Drops from the Hunter.",
        "cost": 0,
        "icon_color": (120, 160, 255),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": True,
        "drop_weight": 0,
        "category": "weapon",
        "equipment_slots": list(WEAPON_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "weapon_id": "hunter_spectral_bow",
        "damage_type": "pierce",
        "is_equippable": True,
        "rarity": RARITY_RARE,
    },
    "hunter_void_blade": {
        "name": "Hunter's Void Blade",
        "description": "Dark energy melee. Drops from the Hunter.",
        "cost": 0,
        "icon_color": (80, 0, 140),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": True,
        "drop_weight": 0,
        "category": "weapon",
        "equipment_slots": list(WEAPON_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "weapon_id": "hunter_void_blade",
        "damage_type": "dark",
        "is_equippable": True,
        "rarity": RARITY_RARE,
    },
    "iron_helmet": {
        "name": "Iron Helmet",
        "description": "Basic head protection for the helmet slot.",
        "cost": 40,
        "icon_color": (145, 155, 170),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["helmet"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
        "theme_tag": "heavy",
    },
    "iron_bracers": {
        "name": "Iron Bracers",
        "description": "Basic arm guards for the arms slot.",
        "cost": 35,
        "icon_color": (165, 145, 120),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["arms"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
        "theme_tag": "heavy",
    },
    "traveler_boots": {
        "name": "Traveler Boots",
        "description": "Basic leg gear for the legs slot.",
        "cost": 30,
        "icon_color": (120, 100, 80),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["legs"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
        "theme_tag": "light",
    },
    "golem_crown": {
        "name": "Golem Crown",
        "description": "Stone-helm crown. +5 HP and +5% crit chance.",
        "cost": 0,
        "icon_color": (170, 145, 110),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["helmet"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
        "theme_tag": "heavy",
    },
    "golem_husk": {
        "name": "Golem Husk",
        "description": "Stone chestplate. +15 HP and 10% damage reduction.",
        "cost": 0,
        "icon_color": (140, 110, 80),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["chest"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
        "theme_tag": "heavy",
    },
    "golem_stride": {
        "name": "Golem Stride",
        "description": "Stone greaves. +5 HP and +5% movement speed.",
        "cost": 0,
        "icon_color": (130, 105, 75),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["legs"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
        "theme_tag": "heavy",
    },
    "golem_fists": {
        "name": "Golem Fists",
        "description": "Stone gauntlets. +5 HP and +5% outgoing damage.",
        "cost": 0,
        "icon_color": (155, 120, 90),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["arms"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
        "theme_tag": "heavy",
    },
    # ── Wayfarer set (light, shop-purchasable) ─────────
    "wayfarer_hood": {
        "name": "Wayfarer Hood",
        "description": "Light hood. +6% magic find.",
        "cost": 50,
        "icon_color": (180, 200, 160),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["helmet"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
        "theme_tag": "light",
    },
    "wayfarer_jerkin": {
        "name": "Wayfarer Jerkin",
        "description": "Light chest wrap. +5% movement speed.",
        "cost": 65,
        "icon_color": (160, 190, 140),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["chest"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
        "theme_tag": "light",
    },
    "wayfarer_wraps": {
        "name": "Wayfarer Wraps",
        "description": "Light arm wraps. +5% attack speed.",
        "cost": 45,
        "icon_color": (170, 195, 150),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["arms"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
        "theme_tag": "light",
    },
    "wayfarer_treads": {
        "name": "Wayfarer Treads",
        "description": "Swift boots. +10% speed, -15% dodge cooldown.",
        "cost": 100,
        "icon_color": (140, 180, 120),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["legs"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_RARE,
        "theme_tag": "light",
    },
    # ── Spellweave set (arcane, boss/chest drops) ──────
    "spellweave_circlet": {
        "name": "Spellweave Circlet",
        "description": "Arcane headband. +8% crit, +1 minimap radius.",
        "cost": 0,
        "icon_color": (190, 140, 230),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["helmet"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_RARE,
        "theme_tag": "arcane",
    },
    "spellweave_robe": {
        "name": "Spellweave Robe",
        "description": "Arcane chest weave. +15% arcane resist.",
        "cost": 0,
        "icon_color": (170, 120, 220),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["chest"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
        "theme_tag": "arcane",
    },
    "spellweave_cuffs": {
        "name": "Spellweave Cuffs",
        "description": "Arcane wrist cuffs. +8% outgoing damage.",
        "cost": 0,
        "icon_color": (200, 150, 240),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["arms"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
        "theme_tag": "arcane",
    },
    "spellweave_slippers": {
        "name": "Spellweave Slippers",
        "description": "Arcane silk slippers. +12% speed, +25% dodge distance.",
        "cost": 0,
        "icon_color": (210, 160, 250),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "equipment",
        "equipment_slots": ["legs"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
        "theme_tag": "arcane",
    },
    # ── Ring accessories (fit all 4 ring slots) ──────────────────────
    "band_of_vigor": {
        "name": "Band of Vigor",
        "description": "+5 max HP.",
        "cost": 60,
        "icon_color": (200, 100, 100),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    "band_of_haste": {
        "name": "Band of Haste",
        "description": "+3% movement speed.",
        "cost": 60,
        "icon_color": (100, 200, 150),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    "band_of_focus": {
        "name": "Band of Focus",
        "description": "+3% crit chance.",
        "cost": 60,
        "icon_color": (150, 180, 240),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    "band_of_grit": {
        "name": "Band of Grit",
        "description": "+10 max HP and +2% damage reduction.",
        "cost": 100,
        "icon_color": (180, 130, 80),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
    },
    "ember_signet": {
        "name": "Ember Signet",
        "description": "+10% fire resist and +3% outgoing damage.",
        "cost": 110,
        "icon_color": (240, 120, 50),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
    },
    "frostbound_ring": {
        "name": "Frostbound Ring",
        "description": "+15% ice resist, +5% speed, +3% crit.",
        "cost": 0,
        "icon_color": (100, 210, 255),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_RARE,
    },
    "viper_loop": {
        "name": "Viper Loop",
        "description": "+15% poison resist and +5% attack speed.",
        "cost": 0,
        "icon_color": (110, 220, 80),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_RARE,
    },
    "stormcoil": {
        "name": "Stormcoil",
        "description": "+20% lightning resist, +8% crit, -3% dodge cooldown.",
        "cost": 0,
        "icon_color": (255, 240, 80),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
    },
    "arcane_circlet_ring": {
        "name": "Arcane Circlet",
        "description": "+20% arcane resist, +5% magic find, +5 max HP.",
        "cost": 0,
        "icon_color": (200, 140, 255),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
    },
    "bloodstone_ring": {
        "name": "Bloodstone Ring",
        "description": "+15% outgoing damage. Restores 5 HP on kill.",
        "cost": 0,
        "icon_color": (200, 40, 40),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_EXQUISITE,
    },
    "wyrm_seal": {
        "name": "Wyrm Seal",
        "description": "+15% all elemental resist, +20 max HP.",
        "cost": 0,
        "icon_color": (230, 80, 50),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_EXOTIC,
    },
    "oathbinder": {
        "name": "Oathbinder",
        "description": "+10% all stats. Grants 1 free dodge per room.",
        "cost": 0,
        "icon_color": (255, 215, 80),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": list(RING_EQUIPMENT_SLOTS),
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_LEGENDARY,
    },
    # ── Pendant accessories (single slot) ────────────────────────────────────
    "tarnished_amulet": {
        "name": "Tarnished Amulet",
        "description": "+5% physical damage resist.",
        "cost": 55,
        "icon_color": (180, 160, 120),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
    },
    "cinder_pendant": {
        "name": "Cinder Pendant",
        "description": "+15% fire resist.",
        "cost": 90,
        "icon_color": (240, 110, 50),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
    },
    "glacial_locket": {
        "name": "Glacial Locket",
        "description": "+15% ice resist.",
        "cost": 90,
        "icon_color": (130, 220, 255),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
    },
    "serpent_charm": {
        "name": "Serpent Charm",
        "description": "+20% poison resist. Cleanses poison on equip.",
        "cost": 0,
        "icon_color": (80, 200, 80),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_RARE,
    },
    "stormcaller_pendant": {
        "name": "Stormcaller Pendant",
        "description": "+20% lightning resist.",
        "cost": 0,
        "icon_color": (220, 230, 80),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_RARE,
    },
    "wardstone": {
        "name": "Wardstone",
        "description": "+25% arcane resist and +5% all-type resist.",
        "cost": 0,
        "icon_color": (190, 130, 255),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_SUPERIOR,
    },
    "aegis_of_the_deep": {
        "name": "Aegis of the Deep",
        "description": "+30% physical resist and +15 max HP.",
        "cost": 0,
        "icon_color": (60, 100, 200),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_EXQUISITE,
    },
    "prismatic_pendant": {
        "name": "Prismatic Pendant",
        "description": "+20% resist to all damage types.",
        "cost": 0,
        "icon_color": (200, 200, 255),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["pendant"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_LEGENDARY,
    },
    # ── Belt accessories (single slot, theme-keyed bonuses) ───────────────────
    "leather_strap": {
        "name": "Leather Strap",
        "description": "+2 max HP per equipped armor piece (any theme).",
        "cost": 50,
        "icon_color": (160, 120, 80),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["belt"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_COMMON,
        "theme_match": None,
    },
    "bulwark_belt": {
        "name": "Bulwark Belt",
        "description": "+3% damage reduction per heavy armor piece.",
        "cost": 100,
        "icon_color": (100, 100, 130),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["belt"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
        "theme_match": "heavy",
    },
    "runner_sash": {
        "name": "Runner's Sash",
        "description": "+3% movement speed per light armor piece.",
        "cost": 100,
        "icon_color": (100, 200, 140),
        "max_owned": 1,
        "can_purchase": True,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["belt"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_UNCOMMON,
        "theme_match": "light",
    },
    "mage_cord": {
        "name": "Mage Cord",
        "description": "+5% arcane resist and +5% magic find per arcane armor piece.",
        "cost": 0,
        "icon_color": (180, 120, 255),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["belt"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_RARE,
        "theme_match": "arcane",
    },
    "phoenix_girdle": {
        "name": "Phoenix Girdle",
        "description": "+5% DR, +4% fire resist, and +2 max HP per heavy armor piece.",
        "cost": 0,
        "icon_color": (255, 140, 30),
        "max_owned": 1,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "category": "accessory",
        "equipment_slots": ["belt"],
        "storage_bucket": "equipment",
        "is_equippable": True,
        "rarity": RARITY_EXOTIC,
        "theme_match": "heavy",
    },
})

ITEM_DATABASE["armor"].update({
    "equipment_slots": ["chest"],
    "storage_bucket": "equipment",
    "is_equippable": True,
})
ITEM_DATABASE["sword_plus"].update({
    "category": "weapon_upgrade",
    "storage_bucket": "upgrade",
    "upgrade_weapon_id": "sword",
    "upgrade_tier": 1,
})
ITEM_DATABASE["spear_plus"].update({
    "category": "weapon_upgrade",
    "storage_bucket": "upgrade",
    "upgrade_weapon_id": "spear",
    "upgrade_tier": 1,
})
ITEM_DATABASE["axe_plus"].update({
    "category": "weapon_upgrade",
    "storage_bucket": "upgrade",
    "upgrade_weapon_id": "axe",
    "upgrade_tier": 1,
})

# Biome-themed challenge-route rewards. Awarded as guaranteed bonus loot when
# the player commits to a trap-gauntlet challenge route. They are loot-only
# (no shop purchase) and never appear in the standard random chest table — the
# only way to earn one is to commit to a challenge route in the matching biome.
ITEM_DATABASE.update({
    "stat_shard": {
        "name": "Boulder Stat Shard",
        "description": "Mud-cavern challenge trophy: store for a future stat boost.",
        "cost": 0,
        "icon_color": (200, 140, 70),
        "max_owned": 5,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "chest_drop_weight": 0,
        "category": "biome_reward",
        "rarity": RARITY_EXOTIC,
    },
    "tempo_rune": {
        "name": "Frost Tempo Rune",
        "description": "Frozen-depths challenge trophy: charges a future tempo rune slot.",
        "cost": 0,
        "icon_color": (160, 210, 255),
        "max_owned": 5,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "chest_drop_weight": 0,
        "category": "biome_reward",
        "rarity": RARITY_EXOTIC,
    },
    "mobility_charge": {
        "name": "Tide Mobility Charge",
        "description": "Sunken-ruins challenge trophy: stores a burst-dash charge for later use.",
        "cost": 0,
        "icon_color": (90, 230, 200),
        "max_owned": 5,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "chest_drop_weight": 0,
        "category": "biome_reward",
        "rarity": RARITY_EXOTIC,
    },
    "prismatic_keystone": {
        "name": "Prismatic Keystone",
        "description": "Crafted at the shop from one trophy of each biome. Long-arc collectible.",
        "cost": 0,
        "icon_color": (235, 200, 255),
        "max_owned": 3,
        "can_purchase": False,
        "can_loot": False,
        "drop_weight": 0,
        "chest_drop_weight": 0,
        "category": "biome_reward",
        "rarity": RARITY_LEGENDARY,
    },
})

for item_data in ITEM_DATABASE.values():
    item_data.setdefault("equipment_slots", [])
    item_data.setdefault("storage_bucket", "inventory")
    item_data.setdefault("weapon_id", None)
    item_data.setdefault("damage_type", None)
    item_data.setdefault("upgrade_weapon_id", None)
    item_data.setdefault("upgrade_tier", 0)
    item_data.setdefault("chest_drop_weight", 0)
    item_data.setdefault("is_equippable", bool(item_data["equipment_slots"]))
    item_data.setdefault("rarity", RARITY_COMMON)
    item_data.setdefault("theme_tag", "")
    item_data.setdefault("theme_match", None)


def rarity_color(item_id: str) -> tuple:
    """Return the RGB color tuple for an item's rarity tier."""
    rarity = ITEM_DATABASE[item_id].get("rarity", RARITY_COMMON)
    return RARITY_COLORS[rarity]


def tier_index(item_id: str) -> int:
    """Return the 0-based sort index for an item's rarity tier (common=0, legendary=6)."""
    rarity = ITEM_DATABASE[item_id].get("rarity", RARITY_COMMON)
    return RARITY_TIERS.index(rarity)


ENEMY_LOOT_TABLE = [
    (item_id, data["drop_weight"])
    for item_id, data in ITEM_DATABASE.items()
    if data["can_loot"] and data["drop_weight"] > 0
]
ENEMY_LOOT_IDS = [item_id for item_id, _weight in ENEMY_LOOT_TABLE]
ENEMY_LOOT_WEIGHTS = [weight for _item_id, weight in ENEMY_LOOT_TABLE]

CHEST_LOOT_TABLE = [
    (item_id, data["chest_drop_weight"])
    for item_id, data in ITEM_DATABASE.items()
    if data["chest_drop_weight"] > 0
]
CHEST_LOOT_IDS = [item_id for item_id, _weight in CHEST_LOOT_TABLE]
CHEST_LOOT_WEIGHTS = [weight for _item_id, weight in CHEST_LOOT_TABLE]

CHEST_COIN_DROP_PROBABILITY = 0.4
_CHEST_TOTAL_LOOT_WEIGHT = sum(CHEST_LOOT_WEIGHTS)
if _CHEST_TOTAL_LOOT_WEIGHT > 0:
    CHEST_CONTENT_TABLE = [("coin", None, CHEST_COIN_DROP_PROBABILITY)]
    CHEST_CONTENT_TABLE.extend(
        (
            "loot",
            item_id,
            (1.0 - CHEST_COIN_DROP_PROBABILITY) * (weight / _CHEST_TOTAL_LOOT_WEIGHT),
        )
        for item_id, weight in CHEST_LOOT_TABLE
    )
else:
    CHEST_CONTENT_TABLE = [("coin", None, 1.0)]

CHEST_CONTENT_ENTRIES = [
    (entry_kind, item_id)
    for entry_kind, item_id, _weight in CHEST_CONTENT_TABLE
]
CHEST_CONTENT_WEIGHTS = [weight for _entry_kind, _item_id, weight in CHEST_CONTENT_TABLE]